### ISSUE TITLE
Regarding module initialization and input format

### ISSUE THREAD

**Issue by swathikirans** [noureldien/timeception#1]
In the example given for the pytorch version of the timeception module, the dimension of the input, including the batch size is required to be given. After going through the definition of the module in "timeception_pytorch.py" file, I believe that the first element of the shape tensor is not used, which means that an arbitrary value can be passed as the first value along with the size of the input tensor. I want to make sure if this is right or not.

Secondly, in the example given, the input tensor applied to the module is of the form BxCxTxWxH, which is the default format for pytorch. However, in the above mentioned file, what I understand is that the input should be of the form BxTxWxHxC (line 238). Which one is the right format for the input applied to the module?

**Comment by noureldien** [comment]
Hi Swathikiran,
Thanks for your interest in our work. 
- For the 1st question, yes, you can use any batch size you want.
- For the 2nd question, you are right. Line 235 there was error
I fixed it, see [here](https://github.com/noureldien/timeception/blob/1f62c6bf04d459ea65f0005f6db55aba0db418c5/nets/timeception_pytorch.py#L236 )

I've never trained timeception using pytorch implementation. All models are trained using keras implementation. I only reimplemented it in pytorch to make it easier for other to use it.

**Comment by swathikirans** [comment]
Thank you for the quick reply.
