### ISSUE TITLE
Use video annotation for finetune model on Charades?

### ISSUE THREAD

**Issue by v-wewei** [noureldien/timeception#13]
Hi, did you use the video annotation for fine tune the model on Charades dataset, i can not find the code for finetune the model ? so , could you pls release the code for finetune the model on charades dataset ?
Thanks very much !

**Comment by noureldien** [comment]
Thanks for asking.
What model are you referring to? Is it backbone CNNs?
I got the fine-tuned backbone CNNs from these repositories:
I3D: https://github.com/piergiaj/pytorch-i3d
2D-ResNet-152: https://github.com/gsig/charades-algorithms
3D-ResNet-101: https://github.com/facebookresearch/video-nonlocal-net
or https://github.com/facebookresearch/video-long-term-feature-banks

**Comment by v-wewei** [comment]
i mean how do you fine tune the model on Charades ?
