### ISSUE TITLE
Links Expired

### ISSUE THREAD

**Issue by spoorgholi74** [noureldien/timeception#18]
Hi, 
Thanks for providing the code.

The links to the pretrained models are expired. I was wondering if you can fix them and if you have the pre-trained weight for more C3D models such as Resnet-34?

**Comment by noureldien** [comment]
Hi Soroosh,

Thanks for your question. I'm sorry that I don't have the pretrained model.
However, the code provided is more than enough to reproduce the results of the paper.

Please let me know if you have any question.
