### ISSUE TITLE
Request for providing the splits file for breakfast action dataset

### ISSUE THREAD

**Issue by dipika-singhania** [noureldien/timeception#19]
Hi,

I read in the paper that for breakfast actions, it uses particular training and test. 
"It contains 1712 videos in total, 1357 for training and 335 for tests."

Wanted to check whether you could provide this division of training and test files? 
Because in the official breakfast action dataset(https://serre-lab.clps.brown.edu/resource/breakfast-actions-dataset/), they mention 4 official split of breakfast actions dataset. But could not find the split file for 1357 training and 335 test dataset. 

Thanking You.
Dipika

**Comment by noureldien** [comment]
Hello Dipika,

Thanks for asking. And thanks for your intrrest on our work.

Here is the split
https://github.com/Maddy12/videograph/blob/master/data/Breakfast/annotation/annot_activities.pkl

And here is the code I used to do the split
https://github.com/Maddy12/videograph/blob/master/datasets/ds_breakfast.py#L120

Thanks,
Nour

**Comment by dipika-singhania** [comment]
Thank you for sharing the same.
