### ISSUE TITLE
models not availble

### ISSUE THREAD

**Issue by NinaCai** [noureldien/timeception#2]
The models are not available to download.

**Comment by noureldien** [comment]
Hi NinaCai,
Thanks again for asking. I'm working as hard as I can to release all trained models. Sorry for any delay.

**Comment by beibeirory** [comment]
Thanks for sharing the code. But the links are invalid. The models are not available to download.

**Comment by Buzz-Beater** [comment]
I'm having the same trouble, is there any update from the authors?

**Comment by noureldien** [comment]
Hi Buzz-Beater and Beibeirory,
Thanks for your e-mail. I can't train Timeception these days. Our researchers are using all GPUs for CVPR submission. I hope you understand.
Thanks,
Nour

**Comment by Jimmy880** [comment]
None of the links of pretrained models are available. Is there any update? @noureldien

**Comment by noureldien** [comment]
Hi Jimmy, thanks for your comment. I'm sorry that I cannot train Timeception.
However, the code provided is more than enough to reproduce the results of the paper.
