### ISSUE TITLE
Frame issue

### ISSUE THREAD

**Issue by Maikuraky** [noureldien/timeception#6]
Now only the keras version of the code, and I found that it is a mix of keras and pytorch

**Comment by noureldien** [comment]
Thanks for your question. Can you please explain more? You can either use Keras or PyTorch. There no code which is a mix of both. Hope it helps!

**Comment by Maikuraky** [comment]
Oh,thanks! You put the two version in the same python file.And what is the version of opencv?

**Comment by noureldien** [comment]
Hi again, no, pytorch and keras implementation are in 2 different files.
I use opencv 3.2
