### ISSUE TITLE
3D-resnet

### ISSUE THREAD

**Issue by CuongNguyen218** [noureldien/timeception#7]
Hi,
I want to use 3d-resnet model as a part of my project. Can you share your code for me ?

**Comment by noureldien** [comment]
Hi Cuong,
Thanks for asking. Sorry, I did not understand your question. Do you want to train Timeception layers on top of 3D-ResNet101? Then start from here
https://github.com/noureldien/timeception/blob/master/experiments/train_keras.py
https://github.com/noureldien/timeception/blob/master/experiments/train_pytorch.py

Or do you want the trained model on Charades? I'm expected to release the trained model soon.

**Comment by CuongNguyen218** [comment]
Hi Noureldien,
Sorry for my unclear question. There are what I am looking for.
Thanks for your help.
