### ISSUE TITLE
Number of frame

### ISSUE THREAD

**Issue by CuongNguyen218** [noureldien/timeception#8]
Hi Noureldien,
I have a question about r3d. As I see when I applied resnet-3d with input size like T x H x W x C, the time dimension T always decreases after some layers. So you set T = ? to get output of 3D-resnet equals 1024 x H x W x C.

**Comment by noureldien** [comment]
Hi,

Thanks for your question. One Timeception layer downsamples the timsteps by a factor of two. So, to get output T=1, you can use 1 Timeception layer with input T=2, or two Timeception layers with input T=4. Please use the code and experiment it. It is really easy to figure it out.

Thanks
